#3 Add SLQ styling
ACMILabs/video-search pull request #4
Opened 2024-09-30 03:10 UTC by sighmon

Resolves #3

Let's add some styling to match the SLQ website.

### Acceptance Criteria
- [x] Add styling to match the SLQ style-guide for their video search

### Relevant design files
* None

### Testing instructions
1. Note styling matches the SLQ style guide as much as possible.

2024-10-15 04:02 UTC, rubyquaildesign requested changes
little issue around html entity escaping when highlighting, otherwise good

2024-10-15 04:02 UTC, rubyquaildesign commented on app/static/js/index.js
> +        segment.innerHTML = highlightedText;
I'd be careful about html element weirdness here here, maybe escape <, >, /, &, and " in the search query before inserting into the span.

2024-10-16 04:47 UTC, sighmon commented on app/static/js/index.js
> +        segment.innerHTML = highlightedText;
@rubyquaildesign Good catch! I'll do it in the backend to avoid weird search results too.

2024-10-28 02:31 UTC, rubyquaildesign approved these changes

2025-04-01 05:52 UTC, merged